id: 45dc87b1-4e20-4061-8838-1be81786e318
name: Aayush's Mighty App
organizationId: 3492f7ec-e1d6-4342-84e9-f42d40e1c05c
isPublic: false
deletedAt: null
isDeployed: false
deployedCommitId: null
isEditable: true
updated: 2023-07-14T21:36:20.686Z
created: 2023-07-14T21:36:20.686Z
folderId: null
creator:
  id: fa7f04cf-3536-451a-bb85-12b2dec32e43
  name: Aayush Shah
userPermissions:
  - manage:applications
  - read:applications
  - publish:applications
  - makePublic:applications
