id: 264d7c93-ab17-46f3-9a9d-5966f6cca064
name: Ahmet's Awesome App
organizationId: 3492f7ec-e1d6-4342-84e9-f42d40e1c05c
isPublic: false
deletedAt: null
isDeployed: false
deployedCommitId: null
isEditable: true
updated: 2023-07-14T20:46:07.297Z
created: 2023-07-14T20:46:07.297Z
folderId: null
creator:
  id: e964c654-767f-4e76-84fe-ceccc60a0bee
  name: Ahmet Kucuk
userPermissions:
  - manage:applications
  - read:applications
  - publish:applications
  - makePublic:applications
