created: 2023-08-31T15:42:51.220Z
creator:
  id: 15507819-c740-45b5-92b7-76b8d33499c2
  name: Aayush Shah
deletedAt: null
deployedAt: null
deployedCommitId: null
folderId: null
id: 8e045c20-83ed-4bae-882f-b7105801abf5
isDeployed: false
isEditable: true
isPublic: false
name: aayush second bugbash app
organizationId: e93953a9-9ee2-410a-8bd9-3bccd3fd3de2
pages:
  - id: dc6fe4fa-9f3e-4e07-8d53-afc2dfbd54a8
    isDefault: true
settings:
  profiles:
    deployed:
      availableProfileIds:
        - 8bcba49a-e391-4d4a-a755-2067afe7ad85
        - 0b000717-9c95-4c33-a007-d8d1f5d58ad1
      defaultProfileId: 8bcba49a-e391-4d4a-a755-2067afe7ad85
    editor:
      availableProfileIds:
        - 8bcba49a-e391-4d4a-a755-2067afe7ad85
        - 0b000717-9c95-4c33-a007-d8d1f5d58ad1
      defaultProfileId: 0b000717-9c95-4c33-a007-d8d1f5d58ad1
    preview:
      availableProfileIds:
        - 8bcba49a-e391-4d4a-a755-2067afe7ad85
        - 0b000717-9c95-4c33-a007-d8d1f5d58ad1
      defaultProfileId: 0b000717-9c95-4c33-a007-d8d1f5d58ad1
updated: 2023-08-31T15:42:57.932Z
userPermissions:
  - manage:applications
  - read:applications
  - publish:applications
  - makePublic:applications
